// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111081557_ICTAWebsiteMig7")]
    partial class ICTAWebsiteMig7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Auth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("F_NAME");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("MailToken")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("MAIL_TOKEN");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("AUTH");
                });

            modelBuilder.Entity("Entities.BaseRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseRuleId")
                        .HasColumnType("int")
                        .HasColumnName("BASE_RULE_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<string>("CoverPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PHOTO");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_TIME");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HASHTAGS");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_TIME");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("VIEW_COUNT");

                    b.HasKey("Id");

                    b.ToTable("BASE_RULES");
                });

            modelBuilder.Entity("Entities.CompOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("APPLICATION_TYPE");

                    b.Property<DateTime>("DateOfApp")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE_OF_APP");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILE_PATH");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("NameSurname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME_SURNAME");

                    b.Property<string>("ToWhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TO_WHOM");

                    b.HasKey("Id");

                    b.ToTable("COMP_OFFER");
                });

            modelBuilder.Entity("Entities.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ANSWER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QUESTION");

                    b.HasKey("Id");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("Entities.Footer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("dateYear")
                        .HasColumnType("int")
                        .HasColumnName("DATE_YEAR");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_UPDATED");

                    b.Property<string>("madeBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MADE_BY");

                    b.Property<string>("roomNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROOM_NO");

                    b.Property<string>("technicalPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TECHNICAL_PHONE");

                    b.HasKey("id");

                    b.ToTable("Footer");
                });

            modelBuilder.Entity("Entities.Novelty.BaseNovelty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AUTHOR_ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<string>("CoverPhotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COVER_PHOTO_URL");

                    b.Property<int>("NoveltyId")
                        .HasColumnType("int")
                        .HasColumnName("NOVELTY_ID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TITLE");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("VIEW_COUNT");

                    b.HasKey("Id");

                    b.ToTable("NOVELTIES");
                });

            modelBuilder.Entity("Entities.Novelty.BaseRulesFilesPhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileOrPhoto")
                        .HasColumnType("int")
                        .HasColumnName("FILE_OR_PHOTO");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILE_PATH");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit")
                        .HasColumnName("IS_TEMPORARY");

                    b.Property<int>("RuleItemId")
                        .HasColumnType("int")
                        .HasColumnName("RULE_ITEM_ID");

                    b.HasKey("Id");

                    b.HasIndex("RuleItemId");

                    b.ToTable("BASE_RULES_FILES_PHOTOS");
                });

            modelBuilder.Entity("Entities.Novelty.NoveltyFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILE_PATH");

                    b.Property<int>("NoveltyItemId")
                        .HasColumnType("int")
                        .HasColumnName("NOVELTY_ITEM_ID");

                    b.HasKey("Id");

                    b.HasIndex("NoveltyItemId");

                    b.ToTable("NOVELTIES_FILES");
                });

            modelBuilder.Entity("Entities.Novelty.NoveltyLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DislikeStatus")
                        .HasColumnType("int")
                        .HasColumnName("DISLIKE_STATUS");

                    b.Property<int>("LikeStatus")
                        .HasColumnType("int")
                        .HasColumnName("LIKE_STATUS");

                    b.Property<int>("NoveltyItemId")
                        .HasColumnType("int")
                        .HasColumnName("NOVELTY_ITEM_ID");

                    b.Property<string>("WhoLikes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WHO_LIKES");

                    b.HasKey("Id");

                    b.HasIndex("NoveltyItemId");

                    b.ToTable("NOVELTIES_LIKE_DISLIKE");
                });

            modelBuilder.Entity("Entities.Regulations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FILE_PATH");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_UPDATED");

                    b.Property<string>("photoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHOTO_PATH");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("id");

                    b.ToTable("Regulations");
                });

            modelBuilder.Entity("Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LINKEDIN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("PHONE");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PHOTO_PATH");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POSITION");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Entities.Novelty.BaseRulesFilesPhotos", b =>
                {
                    b.HasOne("Entities.BaseRules", "BaseRules")
                        .WithMany("BaseRulesFilesPhotos")
                        .HasForeignKey("RuleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseRules");
                });

            modelBuilder.Entity("Entities.Novelty.NoveltyFile", b =>
                {
                    b.HasOne("Entities.Novelty.BaseNovelty", "NoveltyItem")
                        .WithMany("NoveltyFiles")
                        .HasForeignKey("NoveltyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoveltyItem");
                });

            modelBuilder.Entity("Entities.Novelty.NoveltyLike", b =>
                {
                    b.HasOne("Entities.Novelty.BaseNovelty", "NoveltyItem")
                        .WithMany("NoveltyLike")
                        .HasForeignKey("NoveltyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoveltyItem");
                });

            modelBuilder.Entity("Entities.BaseRules", b =>
                {
                    b.Navigation("BaseRulesFilesPhotos");
                });

            modelBuilder.Entity("Entities.Novelty.BaseNovelty", b =>
                {
                    b.Navigation("NoveltyFiles");

                    b.Navigation("NoveltyLike");
                });
#pragma warning restore 612, 618
        }
    }
}
